use_frameworks!

platform :ios, '10.0'

target 'ZZComponent_Example' do
  pod 'ZZComponent', :path => '../'

  target 'ZZComponent_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
